### PR TITLE
Updates numbering

### PR DESCRIPTION
**Pull request by payne-chris-r**

### CODE REVIEW

**Comment by gaand** [comment]
This change probably isn't the right one.  Indenting the code blocks in the list should produce the correct numbering.

**Comment by gaand** [comment]
See https://github.com/ga-wdi-boston/rails-api-relationships-diagnostic/blob/015/alternate/diagnostic.md

**Comment by payne-chris-r** [comment]
I think that's better.

**Comment by raq929** [comment]
This code was cherry-picked into the 016 update.

**Pull request closed without merging**
